name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend - Django Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=root" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Update path if necessary

      - name: Run Migrations
        env:
          DATABASE_URL: mysql://test_user:test_pass@127.0.0.1:3306/test_db
        run: |
          python backend/manage.py migrate

      - name: Run Tests
        run: |
          python backend/manage.py test

  frontend:
    name: Frontend - React Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  deploy:
    name: Deploy Application
    needs: [backend, frontend]  # Run only if backend and frontend jobs pass
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server (Example)
        run: echo "Deploying application..." # Replace with actual deployment steps
